feat: add result upload (#703)
* Add Firebase SDK

* Add docs to configure Firebase

* Add FirebaseService to handle Firebase related tasks

* Add Flutter's multidex support

* Add CI user

* Set env for android-build.yaml

* Refactor Firebase services

* Add ShareButton with 2 share options

* Fix dead link in env-setup-ios.md

* Exclude java from sonar scanner

* Fix issue with multidex

com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.

* Fix UnsupportedError on Windows

* Upload result after finishing integration test

* Rename vars in first_test.dart

* Use file template instead of dart-define

* Update UI for ShareButton

* Add Firebase env vars

* Fix issue with new released python version