feat: add new benchmark Stable Diffusion (#903)
* add scaffold of coco_gen dataset

* test coco_gen

* use smart ptr

* minimal ProcessOutput()

* support float32 output tensor

* Add new benchmark stable_diffusion

* Add dummy_stable_diffusion.tflite

* Add clip_score.cc

* Add generate_tfrecords.py

* Update CaptionRecord

* Add coco_gen.tfrecord

* Compute accuracy

* Format files

* Add notebook to convert CLIP model to TFLite model with resize layer

* Move score prediction from ProcessOutput() to ComputeAccuracy()

* Split clip_score into .h and .cpp files

* Add expected_throughput and expected_accuracy

* Update file paths

* Format files

* refactor TFLite backend to support multiple ML pipelines

* Use custom setting for selecting pipeline

* Update CLIP_Model_to_TFLite.ipynb

* Log record_id for debug purpose

* Refactor benchmark result validity

* Ignore the early-stopping condition for stable_diffusion task

* feat: added stable diffusion pipeline (WIP) (#905)

* feat: added stable diffusion pipeline (WIP)

* - enabled stable diffusion pipeline
- code formatting

* style: code formatting

* style: code formatting

* fix: adjusted inputs and outputs for the stable_diffusion_pipeline

* fix: adjusted sd flow

* fix: added unconditional tokens generation

* chore: adjustments

* Update mode paths for stable_diffusion

* Fix proto/test.cc

* Remove id and image_id from tfrecord file

* Clean up

* Update datasets path

* Delete dummy_stable_diffusion.tflite

* Suggestions for few changes in coco_gen dataset (#908)

* Suggestions for few changes in coco_gen dataset

* Fixing a path

* Update random number seeds

* Format code

* Fix neuron/BUILD file

* Dump raw output to file for COCOGEN (#912)

* Dump output of SD model to file

* Add Python script to convert RGB8 to PNG

* Dump raw output only in accuracy mode

* Disable stable_diffusion task

* Fix Windows build issue

error C2039: '__fs': is not a member of 'std'

* Fix build error on iOS by increasing IPHONEOS_DEPLOYMENT_TARGET to 13.1

error: 'path' is unavailable: introduced in iOS 13.0

* Fix Dart linter error

* Fix build error on iOS by increasing IPHONEOS_DEPLOYMENT_TARGET to 13.1

error: 'path' is unavailable: introduced in iOS 13.0

---------

Co-authored-by: Koan-Sin Tan <koansin.tan@gmail.com>
Co-authored-by: RSMNYS <sergij.r@scopicsoftware.com>
Co-authored-by: Mohit Mundhra <quic_mmundhra@quicinc.com>